### ISSUE TITLE
Minor niggle about timezones.

### ISSUE THREAD

**Issue by CodingMonkeyXYZ** [Civcraft/JukeAlert#18]
Just a suggestion but could we please have the snitch reports print somewhere on them what timezone the timestamps are in please? Ideally (I don't know how easy it would be to do) it should be in the timezone of the player but failing that a label would be nice.

**Comment by ttk2** [comment]
they are in EST right now, custom time zones would have to be set by the
player, possible but not trivial

**Comment by ac7web** [comment]
Sure, didn't expect it would be easy. Could we label them as EST though please? I always forget what timezone it is as it's not my native one and I'm sure I'm not alone here.

**Comment by ttk2** [comment]
I guess that's feasible

**Comment by Maxopoly** [comment]
Plead leave those open, they were never solved

**Comment by CodingMonkeyXYZ** [comment]
Sure my bad, I'll just unsubscribe.

**Comment by waffle-stomper** [comment]
To save characters, would ISO 8601 format timezones (e.g. -05 for EST) be OK for this? 

Maybe it would be best to display it as UTC instead? That should make it easier for anyone not in the same timezone as the server, plus we could save one more character (+0)!

**Comment by Maxopoly** [comment]
I dont think saving characters is that important, unless it's actually a problem to fit it in. Adding EST is a lot clearer than adding -05, because the the meaning of the first one is a lot clearer. Sure formally it's the same, but I'd assume that not everyone is gonna guess right that an additional -5 means the timezone. If we go with adding just another line in the header of the snitch logs, I'd prefer putting both the timezone name and offset there, if there's not enough space for that just the time zone name.

Ideally we would just display everything in the players timezone, but we have no way to directly retrieve that. It's also a lot more effort, it would require adding a command to adjust the timezone and an additional table to keep track of it. Is autodetecting timezone based on ip lookup feasible?

**Comment by ProgrammerDan** [comment]
Probably just best to add EST to the header line; have it a config var. Don't worry about detecting player timezone.

Something like;

`time EST who  what   where`

(I forget the existing format, apologies)

Definitely don't add EST to every time in the list.

**Comment by waffle-stomper** [comment]
>Is autodetecting timezone based on ip lookup feasible?

It looks like there are a few websites offering that service. I don't know how accurate they are though. We might have issues with the volume of requests if the playerbase increases substantially.

> Probably just best to add EST to the header line; have it a config var. Don't worry about detecting player timezone.

Is the server in a timezone with summer time / daylight saving time?

**Comment by ProgrammerDan** [comment]
I hate timezones.

**Comment by ProgrammerDan** [comment]
Yes, it is. So EST/EDT  --  can easily just harvest timezone from Calendar.getInstance();

**Comment by waffle-stomper** [comment]
>I hate timezones.

Give me UTC or give me death! 

>Yes, it is. So EST/EDT -- can easily just harvest timezone from Calendar.getInstance();

Thanks!
